//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IObserver.cpp
//  @ Date : 14.06.2026
//  @ Author : 
//
//


#include "IObserver.h"

class IObserver;


void update(TSubject* subject){};

