//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TSubject.cpp
//  @ Date : 14.06.2026
//  @ Author : 
//
//


#include "TSubject.h"

#include "IObserver.h"

TSubject::TSubject() {
    this->change = false;
}


void TSubject::attach(IObserver* observer) {
    observers.push_back(observer);
}

void TSubject::detach(IObserver* observer) {
    observers.remove(observer);
}

void TSubject::setChange() {
    change = true;
}

void TSubject::notify() {
    if (change) {
        for (IObserver* observer : observers) {
            observer->update(this);
        }
        change = false;
    }
}

