//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TTemperatureAction.cpp
//  @ Date : 14.06.2026
//  @ Author : 
//
//


#include "TTemperatureAction.h"

#include <iostream>

#include "TThermometer.h"

void TTemperatureAction::update(TSubject* subject) {
    TThermometer* thermometer = dynamic_cast<TThermometer*>(subject);

    if (thermometer) {
        float currentTemp = thermometer->getMeasurement();
        if (currentTemp >= 80.0) {
            std::cout << "AKCJA: Pozar! Wzywam sluzby.\n";
        }
        else if (currentTemp > 25.0) {
            std::cout << "AKCJA: Zbyt goraco! Wlaczam klimatyzacje.\n";
        }
        else if (currentTemp < 19.0) {
            std::cout << "AKCJA: Zbyt zimno! Wlaczam ogrzewanie.\n";
        }
        else {
            std::cout << "AKCJA: Temperatura optymalna. Brak akcji.\n";
        }
    }
}
