//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TThermometer.cpp
//  @ Date : 14.06.2026
//  @ Author : 
//
//


#include "TThermometer.h"

TThermometer::TThermometer() {
    this->temperature = 20.0;
}

void TThermometer::setMeasurement(float newTemp) {
    if (temperature != newTemp) {
        temperature = newTemp;
        setChange();
        notify();
    }
}

float TThermometer::getMeasurement(){
    return temperature;
}

