//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : IObserver.cs
//  @ Date : 14.06.2026
//  @ Author : 
//
//


public class IObserver {
	~IObserver(){
	}
	public void update(:TSubject*):void(){
	}
}
