//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TSubject.cs
//  @ Date : 14.06.2026
//  @ Author : 
//
//


public class TSubject {
	private list<IObserver*> observers ;
	private object change: bool ;
	public TSubject(){
	}
	~TSubject(){
	}
	public void attach(:IObserver*):void(){
	}
	public void detach(:IObserver*):void(){
	}
	public void notify():void(){
	}
	public void setChange(){
	}
}
