//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TTemperatureAction.cs
//  @ Date : 14.06.2026
//  @ Author : 
//
//


public class TTemperatureAction : IObserver{
	public void update(TSubject* ){
	}
}
