//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : TThermometer.cs
//  @ Date : 14.06.2026
//  @ Author : 
//
//


public class TThermometer : TSubject, TSubject{
	private float temperature ;
	public TRoom(){
	}
	public void() setMesurement(float newTemp){
	}
	public void getMesurement():int(){
	}
}
