//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IObserver.h
//  @ Date : 14.06.2026
//  @ Author : 
//
//


#if !defined(_IOBSERVER_H)
#define _IOBSERVER_H


class TSubject;

class IObserver {
public:
	virtual ~IObserver() = default;
	virtual void update(TSubject* subject) = 0;
};

#endif  //_IOBSERVER_H
