//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TTemperatureAction.h
//  @ Date : 14.06.2026
//  @ Author : 
//
//


#if !defined(_TTEMPERATUREACTION_H)
#define _TTEMPERATUREACTION_H

#include "IObserver.h"

class TTemperatureAction : public IObserver {
public:
	void update(TSubject* ) override;
	void setHeating(bool status);
	void setAC(bool status);
	void setAlarm(bool status);
};

#endif  //_TTEMPERATUREACTION_H
