//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TThermometer.h
//  @ Date : 14.06.2026
//  @ Author : 
//
//


#if !defined(_TTHERMOMETER_H)
#define _TTHERMOMETER_H

#include "TSubject.h"

class TThermometer : public TSubject {
public:
	TThermometer();
	void setMeasurement(float newTemp);
	float getMeasurement();
private:
	float temperature;
};

#endif  //_TTHERMOMETER_H
